// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {downloader} from '../models';

export function AddDownload(arg1:string,arg2:string):Promise<downloader.Download>;

export function CancelDownload(arg1:string):Promise<void>;

export function GetCompletedDownloads():Promise<Array<downloader.Download>>;

export function GetConfig():Promise<downloader.Config>;

export function GetDownloads():Promise<Array<downloader.Download>>;

export function PauseDownload(arg1:string):Promise<void>;

export function ProbeDownload(arg1:string):Promise<downloader.DownloadInfo>;

export function ResumeDownload(arg1:string):Promise<void>;

export function RevealFile(arg1:string):Promise<void>;

export function UpdateConfig(arg1:downloader.Config):Promise<downloader.Config>;
